thanksgiving_wishes = [
    "On this special day of Thanksgiving, I want to express my heartfelt gratitude to you for all the love, support, and joy you bring into my life. May your heart be filled with warmth, and your home overflow with laughter, happiness, and delicious food. Have a wonderful Thanksgiving surrounded by loved ones!",
    "As we gather around the table this Thanksgiving, let's remember to be grateful for the little things in life that often go unnoticed. I am thankful for you, and I cherish the memories we've shared. Wishing you a Thanksgiving filled with love, peace, and plenty of blessings.",
    "Happy Thanksgiving! May this holiday bring you all the joy and peace you deserve. May your heart be filled with gratitude, and may you always find blessings in every step you take. Thank you for being part of my life and for making it brighter each day!",
    "On this Thanksgiving, I'm reminded of how fortunate I am to have you in my life. Thank you for the warmth, kindness, and love you share with everyone around you. May this holiday season bring you endless joy, peace, and precious moments with those who matter most.",
    "Gratitude is a powerful thing, and today, I want to take a moment to thank you for being such an incredible part of my life. Your kindness and generosity have been a constant source of inspiration. May your Thanksgiving be as sweet and wonderful as you are!",
    "Happy Thanksgiving to you and your family! I am incredibly grateful for your friendship and support. May your holiday be filled with laughter, good food, and cherished moments with those you love. Here's to a season of gratitude, happiness, and abundance!",
    "Sending you my warmest wishes this Thanksgiving. I am truly thankful for the special bond we share and for all the moments we've spent together. May your Thanksgiving be filled with blessings, and may you continue to shine bright in all that you do.",
    "Thanksgiving is a time to count our blessings, and I feel so fortunate to have you in my life. Your kindness, wisdom, and love make every day brighter. I hope your Thanksgiving is filled with everything that brings you joy and contentment. Enjoy every moment of this beautiful holiday!",
    "This Thanksgiving, I am beyond grateful for the love and support you have shown me. You make the world a better place with your kindness and positive energy. May your heart be full of peace and gratitude today and always. Wishing you a beautiful, memorable holiday!",
    "As we celebrate Thanksgiving today, I want to take a moment to reflect on all the blessings in my life—one of which is you. Thank you for your endless love, generosity, and care. May your holiday season be filled with peace, joy, and wonderful memories.",
    "Happy Thanksgiving to someone who makes life a little brighter with each passing day. I am so grateful for all the moments we've shared and the memories we've created. Wishing you a Thanksgiving full of joy, laughter, and the warmth of family and friends.",
    "Thanksgiving is a time to reflect on all we have and all we are grateful for. I'm incredibly thankful for your friendship, love, and all the good times we've had together. Wishing you a holiday filled with everything that makes you happy, and may your heart be overflowing with gratitude.",
    "This Thanksgiving, I want to let you know how much you mean to me. Your kindness and unwavering support have been a true blessing in my life. May your day be filled with love, laughter, and delicious food, and may you always be surrounded by those who lift you up.",
    "Thanksgiving is a time to give thanks, and I am so thankful for you and the special role you play in my life. Your generosity and love inspire me every day. May your Thanksgiving be filled with beautiful moments, cherished memories, and a heart full of gratitude.",
    "As we gather with family and friends this Thanksgiving, I want to take a moment to thank you for the kindness and love you bring into my life. You make everything better, and I am forever grateful. May your holiday season be filled with peace, joy, and wonderful memories.",
    "Happy Thanksgiving! I am so blessed to have you in my life. Your love, generosity, and support are constant reminders of how lucky I am. May your Thanksgiving be filled with laughter, love, and the warmth of those who care about you the most.",
    "On this beautiful day of Thanksgiving, I want to thank you for the many ways you make my life richer and more meaningful. Your love, compassion, and friendship are gifts that I will forever treasure. May your heart be full of peace and your home filled with love today and always.",
    "As we celebrate this Thanksgiving, I am filled with gratitude for all the amazing people in my life—especially you. Your presence in my life is a true blessing, and I am thankful for the laughter, memories, and love we share. Wishing you a holiday filled with everything your heart desires.",
    "On this day of thanks, I want to thank you for being such a light in my life. Your love and support mean the world to me. May your Thanksgiving be as amazing as you are, and may you feel surrounded by warmth, love, and endless blessings.",
    "Thanksgiving is a time to appreciate what we have and the people who make our lives so much richer. I am so thankful for you and everything you do. Your kindness, generosity, and love are deeply appreciated. Wishing you a Thanksgiving filled with peace, joy, and all your favorite things."
]

# Create text files
for i, wish in enumerate(thanksgiving_wishes, 1):
    with open(f"{i}.txt", "w") as file:
        file.write(wish)